### ISSUE TITLE
Unable to build latest commit

### ISSUE THREAD

**Issue by addisonwebb** [Microsoft/mobile-center-cli#184]
It seems the [latest commit](https://github.com/Microsoft/mobile-center-cli/commit/ba8060524c2bd1001f81fbca56d663797ea59f51) introduced an error that prevents the application from building. If I change my working copy to the previous commit (`926542b44889c6791c2252099978ca65515f0da3`) I am able to build without a problem. 

#### Node Version
v7.10.0

#### NPM Version
v4.2.0

#### Steps to Reproduce:
1. Clone repository
2. Run `npm install`

#### Log File
[2017-05-18T01_25_45_231Z-debug.txt](https://github.com/Microsoft/mobile-center-cli/files/1009515/2017-05-18T01_25_45_231Z-debug.txt)

#### Output
```
[redacted]:mobile-center-cli [redacted]$ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> mobile-center-cli@0.8.0 prepublish [redacted]/mobile-center-cli
> gulp prepublish

module.js:472
    throw err;
    ^

Error: Cannot find module '../dist/util/commandline/option-decorators'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([redacted]/mobile-center-cli/scripts/autocomplete-tree.js:4:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mobile-center-cli@0.8.0 prepublish: `gulp prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mobile-center-cli@0.8.0 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mobile-center-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mobile-center-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mobile-center-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/[redacted]/.npm/_logs/2017-05-18T01_25_45_231Z-debug.log
```

**Comment by christav** [comment]
Fixed via #185
