### ISSUE TITLE
log-flow command fails

### ISSUE THREAD

**Issue by addisonwebb** [Microsoft/mobile-center-cli#188]
When trying to use the new `analytics log-flow` command I only get back an error stating the logs failed to load.

#### Example Output:
```
$ node dist/index.js analytics log-flow --app "user/App-Name"
Command failed: failed to load the logs
```

**Comment by bryukov** [comment]
@addisonwebb Unfortunately, I have not been able to reproduce the issue. Can you, please, execute `export DEBUG=*` to enable the debug mode, run `analytics log-flow` again and post the output here? You can disable the debug mode by executing `export DEBUG=` afterwards.

**Comment by addisonwebb** [comment]
```
$ node dist/index.js analytics log-flow --app "bio-awebb/[...]"
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'debug', undefined ] +0ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'format', undefined ] +3ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'token', undefined ] +1ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'environmentName', undefined ] +0ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'help', undefined ] +1ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'quiet', undefined ] +0ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'version', undefined ] +4ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ Command {}, 'disableTelemetry', undefined ] +0ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ AppCommand {}, 'appOption', undefined ] +2ms
  mobile-center-cli:util:commandline:command-finder Checking stats for [...]/mobile-center-cli/dist/commands +6ms
  mobile-center-cli:util:commandline:command-runner Loading command analytics,log-flow,--app,bio-awebb/[...] +1ms
  mobile-center-cli:util:commandline:command-finder Looking for command [ 'analytics',
  mobile-center-cli:util:commandline:command-finder   'log-flow',
  mobile-center-cli:util:commandline:command-finder   '--app',
  mobile-center-cli:util:commandline:command-finder   'bio-awebb/[...]' ] +1ms
  mobile-center-cli:util:commandline:command-finder Checking legality of 'analytics' +0ms
  mobile-center-cli:util:commandline:command-finder Checking legality of 'log-flow' +0ms
  mobile-center-cli:util:commandline:command-finder Checking legality of '--app' +0ms
  mobile-center-cli:util:commandline:command-finder Looking for 'log-flow' in directory '[...]/mobile-center-cli/dist/commands/analytics' +0ms
  mobile-center-cli:util:commandline:command-finder Checking stats for [...]/mobile-center-cli/dist/commands/analytics +0ms
  mobile-center-cli:util:commandline:command-finder Checking stats for [...]/mobile-center-cli/dist/commands/analytics/log-flow +0ms
  mobile-center-cli:util:commandline:command-finder Command 'analytics log-flow.js' found at [...]/mobile-center-cli/dist/commands/analytics/log-flow.js +1ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ ShowLogFlowCommand {}, 'logsCount', undefined ] +2ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ ShowLogFlowCommand {}, 'installationId', undefined ] +0ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 3 arguments: [ ShowLogFlowCommand {}, 'showContinuously', undefined ] +0ms
  mobile-center-cli:util:commandline:option-decorators @help decorator called with 1 arguments: [ { [Function: ShowLogFlowCommand] delayBetweenRequests: 3000 } ] +0ms
  mobile-center-cli:util:commandline:command-runner Command loading completed, result = { commandFactory: { [Function: ShowLogFlowCommand] delayBetweenRequests: 3000 },
  mobile-center-cli:util:commandline:command-runner   commandParts: [ 'analytics', 'log-flow' ],
  mobile-center-cli:util:commandline:command-runner   args: [ '--app', 'bio-awebb/[...]' ],
  mobile-center-cli:util:commandline:command-runner   commandPath: '[...]/mobile-center-cli/dist/commands/analytics/log-flow.js' } +0ms
  mobile-center-cli:util:commandline:option-parser Parser called with 4 args: [ { debug: 
  mobile-center-cli:util:commandline:option-parser      { longName: 'debug',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Output additional debug information for this command' },
  mobile-center-cli:util:commandline:option-parser     format: 
  mobile-center-cli:util:commandline:option-parser      { hasArg: true,
  mobile-center-cli:util:commandline:option-parser        helpText: 'Format of output for this command: json',
  mobile-center-cli:util:commandline:option-parser        longName: 'output' },
  mobile-center-cli:util:commandline:option-parser     token: 
  mobile-center-cli:util:commandline:option-parser      { hasArg: true,
  mobile-center-cli:util:commandline:option-parser        helpText: 'API Token to use for this command',
  mobile-center-cli:util:commandline:option-parser        longName: 'token' },
  mobile-center-cli:util:commandline:option-parser     environmentName: 
  mobile-center-cli:util:commandline:option-parser      { hasArg: true,
  mobile-center-cli:util:commandline:option-parser        helpText: 'Environment to connect to when using api token',
  mobile-center-cli:util:commandline:option-parser        longName: 'env' },
  mobile-center-cli:util:commandline:option-parser     help: 
  mobile-center-cli:util:commandline:option-parser      { longName: 'help',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Display help for this command',
  mobile-center-cli:util:commandline:option-parser        shortName: 'h' },
  mobile-center-cli:util:commandline:option-parser     quiet: 
  mobile-center-cli:util:commandline:option-parser      { longName: 'quiet',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Auto-confirm any requests, do not prompt for input' },
  mobile-center-cli:util:commandline:option-parser     version: 
  mobile-center-cli:util:commandline:option-parser      { longName: 'version',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Display command\'s version',
  mobile-center-cli:util:commandline:option-parser        shortName: 'v' },
  mobile-center-cli:util:commandline:option-parser     disableTelemetry: 
  mobile-center-cli:util:commandline:option-parser      { longName: 'disable-telemetry',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Do not send any CLI telemetry for this command, overriding defaults' },
  mobile-center-cli:util:commandline:option-parser     appOption: 
  mobile-center-cli:util:commandline:option-parser      { hasArg: true,
  mobile-center-cli:util:commandline:option-parser        helpText: 'Specify application for command to act on',
  mobile-center-cli:util:commandline:option-parser        longName: 'app',
  mobile-center-cli:util:commandline:option-parser        shortName: 'a' },
  mobile-center-cli:util:commandline:option-parser     logsCount: 
  mobile-center-cli:util:commandline:option-parser      { hasArg: true,
  mobile-center-cli:util:commandline:option-parser        longName: 'num-logs',
  mobile-center-cli:util:commandline:option-parser        shortName: 'l',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Introduce the number of logs (max 100) that are being displayed, default number is 100' },
  mobile-center-cli:util:commandline:option-parser     installationId: 
  mobile-center-cli:util:commandline:option-parser      { hasArg: true,
  mobile-center-cli:util:commandline:option-parser        longName: 'install-id',
  mobile-center-cli:util:commandline:option-parser        shortName: 'i',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Filter the logs by install ID' },
  mobile-center-cli:util:commandline:option-parser     showContinuously: 
  mobile-center-cli:util:commandline:option-parser      { longName: 'continue',
  mobile-center-cli:util:commandline:option-parser        shortName: 'c',
  mobile-center-cli:util:commandline:option-parser        helpText: 'Continue to return logs, press Ctrl+C to exit' } },
  mobile-center-cli:util:commandline:option-parser   [],
  mobile-center-cli:util:commandline:option-parser   ShowLogFlowCommand {
  mobile-center-cli:util:commandline:option-parser     additionalSupportedOutputFormats: { json: [Function: setFormatJson] } },
  mobile-center-cli:util:commandline:option-parser   [ '--app', 'bio-awebb/[...]' ] ] +3ms
  mobile-center-cli:util:commandline:option-parser Parsing command line --app bio-awebb/[...] +0ms
  mobile-center-cli:util:commandline:option-parser Raw parsed command line = { _: [],
  mobile-center-cli:util:commandline:option-parser   debug: false,
  mobile-center-cli:util:commandline:option-parser   h: false,
  mobile-center-cli:util:commandline:option-parser   help: false,
  mobile-center-cli:util:commandline:option-parser   quiet: false,
  mobile-center-cli:util:commandline:option-parser   v: false,
  mobile-center-cli:util:commandline:option-parser   version: false,
  mobile-center-cli:util:commandline:option-parser   'disable-telemetry': false,
  mobile-center-cli:util:commandline:option-parser   c: false,
  mobile-center-cli:util:commandline:option-parser   continue: false,
  mobile-center-cli:util:commandline:option-parser   app: 'bio-awebb/[...]',
  mobile-center-cli:util:commandline:option-parser   a: 'bio-awebb/[...]' } +2ms
  mobile-center-cli:util:commandline:command Starting command with path [...]/mobile-center-cli/dist/commands/analytics/log-flow.js, command analytics,log-flow +0ms
  mobile-center-cli:util:commandline:command Initial execution of command +1ms
  mobile-center-cli:util:profile:profile Getting current user from profile +2ms
  mobile-center-cli:util:profile:profile No current user, loading from file +0ms
  mobile-center-cli:util:profile:profile Loading profile from /Users/[...]/.mobile-center-cli/profile.json +0ms
  mobile-center-cli:util:profile:profile Profile file loaded +0ms
  mobile-center-cli:util:commandline:command Creating mobile center client for command for current logged in user +0ms
  mobile-center-cli:util:apis:create-client Creating client from user for user ProfileImpl {
  mobile-center-cli:util:apis:create-client   userId: '[...]',
  mobile-center-cli:util:apis:create-client   userName: 'bio-awebb',
  mobile-center-cli:util:apis:create-client   displayName: '[...]',
  mobile-center-cli:util:apis:create-client   email: '[...]',
  mobile-center-cli:util:apis:create-client   environment: undefined,
  mobile-center-cli:util:apis:create-client   defaultApp: undefined,
  mobile-center-cli:util:apis:create-client   tokenSuppliedByUser: false } +1ms
  mobile-center-cli:util:apis:mobile-center-client-credentials Constructor with getToken = () => user.accessToken of type function +0ms
  mobile-center-cli:util:apis:create-client Creating client options, isDebug = false +0ms
  mobile-center-cli:commands:analytics:log-flow Loading logs +7ms
  mobile-center-cli:util:apis:mobile-center-client-credentials Getting token for request +1ms
  mobile-center-cli:util:token-store:osx:osx-token-store stdout for security program = "keychain: "/Users/[...]/Library/Keychains/login.keychain-db"
  mobile-center-cli:util:token-store:osx:osx-token-store version: 512
  mobile-center-cli:util:token-store:osx:osx-token-store class: "genp"
  mobile-center-cli:util:token-store:osx:osx-token-store attributes:
  mobile-center-cli:util:token-store:osx:osx-token-store     0x00000007 <blob>="mobile-center-cli"
  mobile-center-cli:util:token-store:osx:osx-token-store     0x00000008 <blob>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "acct"<blob>="bio-awebb"
  mobile-center-cli:util:token-store:osx:osx-token-store     "cdat"<timedate>=0x32303137303531393033333431315A00  "20170519033411Z\000"
  mobile-center-cli:util:token-store:osx:osx-token-store     "crtr"<uint32>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "cusi"<sint32>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "desc"<blob>="mobile-center cli password"
  mobile-center-cli:util:token-store:osx:osx-token-store     "gena"<blob>="[...]"
  mobile-center-cli:util:token-store:osx:osx-token-store     "icmt"<blob>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "invi"<sint32>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "mdat"<timedate>=0x32303137303531393033333431315A00  "20170519033411Z\000"
  mobile-center-cli:util:token-store:osx:osx-token-store     "nega"<sint32>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "prot"<blob>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "scrp"<sint32>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store     "svce"<blob>="mobile-center-cli"
  mobile-center-cli:util:token-store:osx:osx-token-store     "type"<uint32>=<NULL>
  mobile-center-cli:util:token-store:osx:osx-token-store " +31ms
  mobile-center-cli:util:token-store:osx:osx-token-store parsing stdout +0ms
  mobile-center-cli:util:token-store:osx:osx-token-store Pushing output into parsing stream +4ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [keychain: "/Users/[...]/Library/Keychains/login.keychain-db"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser matched root line +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding root attribute keychain with value /Users/[...]/Library/Keychains/login.keychain-db to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [version: 512] +1ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser matched root line +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding root attribute version with value  512 to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [class: "genp"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser matched root line +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding root attribute class with value genp to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [attributes:] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser matched root line +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser now in attributes +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    0x00000007 <blob>="mobile-center-cli"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    0x00000008 <blob>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "acct"<blob>="bio-awebb"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding attribute acct with value bio-awebb to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "cdat"<timedate>=0x32303137303531393033333431315A00  "20170519033411Z\000"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding attribute cdat with value 20170519033411Z\000 to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "crtr"<uint32>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "cusi"<sint32>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "desc"<blob>="mobile-center cli password"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding attribute desc with value mobile-center cli password to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "gena"<blob>="[...]"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding attribute gena with value [...] to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "icmt"<blob>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "invi"<sint32>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "mdat"<timedate>=0x32303137303531393033333431315A00  "20170519033411Z\000"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding attribute mdat with value 20170519033411Z\000 to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "nega"<sint32>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "prot"<blob>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "scrp"<sint32>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "svce"<blob>="mobile-center-cli"] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser adding attribute svce with value mobile-center-cli to object +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [    "type"<uint32>=<NULL>] +0ms
  mobile-center-cli:util:token-store:osx:osx-keychain-parser Parsing line [] +0ms
  mobile-center-cli:util:token-store:osx:osx-token-store got data on key lookup: { keychain: '/Users/[...]/Library/Keychains/login.keychain-db',
  mobile-center-cli:util:token-store:osx:osx-token-store   version: ' 512',
  mobile-center-cli:util:token-store:osx:osx-token-store   class: 'genp',
  mobile-center-cli:util:token-store:osx:osx-token-store   acct: 'bio-awebb',
  mobile-center-cli:util:token-store:osx:osx-token-store   cdat: '20170519033411Z\\000',
  mobile-center-cli:util:token-store:osx:osx-token-store   desc: 'mobile-center cli password',
  mobile-center-cli:util:token-store:osx:osx-token-store   gena: '[...]',
  mobile-center-cli:util:token-store:osx:osx-token-store   mdat: '20170519033411Z\\000',
  mobile-center-cli:util:token-store:osx:osx-token-store   svce: 'mobile-center-cli' } +1ms
  mobile-center-cli:util:apis:mobile-center-client-credentials got token [...] of type string +1ms
| Loading logs...  mobile-center-cli:commands:analytics:log-flow Failed to load the logs - { Error: Error "Error: 'type': 'start_service_log'  in 'result.logs' is not a valid discriminator as a corresponding model class for the disciminator 'Log.start_service_log' was not found in this.models.discriminators object." occurred in deserializing the responseBody - "{"exceeded_max_limit":false,"last_received_log_timestamp":"2017-05-19T03:37:36.961Z","logs":[{"services":[],"type":"start_service_log","timestamp":"2017-05-19T03:37:31.099Z","install_id":"8a26e082-2318-4d10-b638-01e71b19940a","device":{"sdk_version":"0.6.1","wrapper_sdk_version":"None","wrapper_sdk_name":"None","model":"iPhone8,1","oem_name":"Apple","os_name":"iOS","os_version":"10.3.2","locale":"en_US","time_zone_offset":-300,"screen_size":"1334x750","app_version":"1.2","carrier_name":"T-Mobile","carrier_country":"us","app_build":"235","app_namespace":"[...].[...]"}},{"session_id":"afba2401-3d39-4dc3-882f-465abfdcccd2","type":"start_session","timestamp":"2017-05-19T03:37:30.67Z","install_id":"8a26e082-2318-4d10-b638-01e71b19940a","device":{"sdk_version":"0.6.1","wrapper_sdk_version":"None","wrapper_sdk_name":"None","model":"iPhone8,1","oem_name":"Apple","os_name":"iOS","os_version":"10.3.2","locale":"en_US","time_zone_offset":-300,"screen_size":"1334x750","app_version":"1.2","carrier_name":"T-Mobile","carrier_country":"us","app_build":"235","app_namespace":"[...].[...]"}},{"session_id":"afba2401-3d39-4dc3-882f-465abfdcccd2","id":"b7a64567-cd80-47f5-96e3-8fab12749f79","name":"user_action","properties":{"identifier":"[...].analytics.action.game.start_1_team_game"},"type":"event","timestamp":"2017-05-19T03:37:33.571Z","install_id":"8a26e082-2318-4d10-b638-01e71b19940a","device":{"sdk_version":"0.6.1","wrapper_sdk_version":"None","wrapper_sdk_name":"None","model":"iPhone8,1","oem_name":"Apple","os_name":"iOS","os_version":"10.3.2","locale":"en_US","time_zone_offset":-300,"screen_size":"1334x750","app_version":"1.2","carrier_name":"T-Mobile","carrier_country":"us","app_build":"235","app_namespace":"[...].[...]"}}]}"
  mobile-center-cli:commands:analytics:log-flow     at [...]/mobile-center-cli/dist/util/apis/generated/operations/analytics.js:1315:36
  mobile-center-cli:commands:analytics:log-flow     at retryCallback ([...]/mobile-center-cli/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:85:9)
  mobile-center-cli:commands:analytics:log-flow     at retryCallback ([...]/mobile-center-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:135:9)
  mobile-center-cli:commands:analytics:log-flow     at handleRedirect ([...]/mobile-center-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
  mobile-center-cli:commands:analytics:log-flow     at Request._callback ([...]/mobile-center-cli/node_modules/ms-rest/lib/requestPipeline.js:126:16)
  mobile-center-cli:commands:analytics:log-flow     at Request.self.callback ([...]/mobile-center-cli/node_modules/ms-rest/node_modules/request/request.js:187:22)
  mobile-center-cli:commands:analytics:log-flow     at emitTwo (events.js:106:13)
  mobile-center-cli:commands:analytics:log-flow     at Request.emit (events.js:194:7)
  mobile-center-cli:commands:analytics:log-flow     at Request.<anonymous> ([...]/mobile-center-cli/node_modules/ms-rest/node_modules/request/request.js:1044:10)
  mobile-center-cli:commands:analytics:log-flow     at emitOne (events.js:101:20)
  mobile-center-cli:commands:analytics:log-flow   request: 
  mobile-center-cli:commands:analytics:log-flow    { rawResponse: false,
  mobile-center-cli:commands:analytics:log-flow      queryString: {},
  mobile-center-cli:commands:analytics:log-flow      url: 'https://api.mobile.azure.com/v0.1/apps/bio-awebb/[...]/analytics/log_flow',
  mobile-center-cli:commands:analytics:log-flow      method: 'GET',
  mobile-center-cli:commands:analytics:log-flow      headers: 
  mobile-center-cli:commands:analytics:log-flow       { 'Content-Type': 'application/json; charset=utf-8',
  mobile-center-cli:commands:analytics:log-flow         'user-agent': 'mobile-centerCli/0.8.0 NodeJS/v7.10.0 darwin/16.6.0',
  mobile-center-cli:commands:analytics:log-flow         'x-api-token': '[...]' },
  mobile-center-cli:commands:analytics:log-flow      body: null },
  mobile-center-cli:commands:analytics:log-flow   response: 
  mobile-center-cli:commands:analytics:log-flow    { body: '{"exceeded_max_limit":false,"last_received_log_timestamp":"2017-05-19T03:37:36.961Z","logs":[{"services":[],"type":"start_service_log","timestamp":"2017-05-19T03:37:31.099Z","install_id":"8a26e082-2318-4d10-b638-01e71b19940a","device":{"sdk_version":"0.6.1","wrapper_sdk_version":"None","wrapper_sdk_name":"None","model":"iPhone8,1","oem_name":"Apple","os_name":"iOS","os_version":"10.3.2","locale":"en_US","time_zone_offset":-300,"screen_size":"1334x750","app_version":"1.2","carrier_name":"T-Mobile","carrier_country":"us","app_build":"235","app_namespace":"[...].[...]"}},{"session_id":"afba2401-3d39-4dc3-882f-465abfdcccd2","type":"start_session","timestamp":"2017-05-19T03:37:30.67Z","install_id":"8a26e082-2318-4d10-b638-01e71b19940a","device":{"sdk_version":"0.6.1","wrapper_sdk_version":"None","wrapper_sdk_name":"None","model":"iPhone8,1","oem_name":"Apple","os_name":"iOS","os_version":"10.3.2","locale":"en_US","time_zone_offset":-300,"screen_size":"1334x750","app_version":"1.2","carrier_name":"T-Mobile","carrier_country":"us","app_build":"235","app_namespace":"[...].[...]"}},{"session_id":"afba2401-3d39-4dc3-882f-465abfdcccd2","id":"b7a64567-cd80-47f5-96e3-8fab12749f79","name":"user_action","properties":{"identifier":"[...].analytics.action.game.start_1_team_game"},"type":"event","timestamp":"2017-05-19T03:37:33.571Z","install_id":"8a26e082-2318-4d10-b638-01e71b19940a","device":{"sdk_version":"0.6.1","wrapper_sdk_version":"None","wrapper_sdk_name":"None","model":"iPhone8,1","oem_name":"Apple","os_name":"iOS","os_version":"10.3.2","locale":"en_US","time_zone_offset":-300,"screen_size":"1334x750","app_version":"1.2","carrier_name":"T-Mobile","carrier_country":"us","app_build":"235","app_namespace":"[...]]"}}]}',
  mobile-center-cli:commands:analytics:log-flow      headers: 
  mobile-center-cli:commands:analytics:log-flow       { 'access-control-allow-origin': '*',
  mobile-center-cli:commands:analytics:log-flow         'transfer-encoding': 'chunked',
  mobile-center-cli:commands:analytics:log-flow         'content-type': 'application/json; charset=utf-8',
  mobile-center-cli:commands:analytics:log-flow         server: 'Microsoft-HTTPAPI/2.0',
  mobile-center-cli:commands:analytics:log-flow         date: 'Fri, 19 May 2017 12:48:05 GMT',
  mobile-center-cli:commands:analytics:log-flow         connection: 'close',
  mobile-center-cli:commands:analytics:log-flow         'strict-transport-security': 'max-age=15768000' },
  mobile-center-cli:commands:analytics:log-flow      statusCode: 200 } } +1s
Command failed: failed to load the logs
```

**Comment by christav** [comment]
@addisonwebb Just so you know, we've found a fairly serious issue that will require a rethink about how we deal with the log data. To keep moving forward, we've removed the command from the CLI from the moment and will bring it back once we figure out how to deal with the issue. It's not gone permanently, it just needs a little more bake time.
